### ISSUE TITLE
Error during install step "python manage.py migrate"

### ISSUE THREAD

**Issue by JohnKirk1337** [Crivella/ocr_translate#32]
The following error occurs during the installation procedure. I followed the "from github" instructions. Up until that step, it was all fine. 

```
(ocr) PS C:\OCR\ocr\ocr_translate> python manage.py migrate
Traceback (most recent call last):
  File "C:\OCR\ocr\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: ocr_translate_optiondict

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\OCR\ocr\ocr_translate\manage.py", line 22, in <module>
    main()
  File "C:\OCR\ocr\ocr_translate\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\OCR\ocr\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\OCR\ocr\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\OCR\ocr\Lib\site-packages\django\core\management\base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\OCR\ocr\Lib\site-packages\django\core\management\base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\core\management\base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\core\management\commands\migrate.py", line 100, in handle
    self.check(databases=[database])
  File "C:\OCR\ocr\Lib\site-packages\django\core\management\base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\core\checks\urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\core\checks\urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jcaiq\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\OCR\ocr\ocr_translate\mysite\urls.py", line 39, in <module>
    path('', include('ocr_translate.urls')),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jcaiq\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\OCR\ocr\ocr_translate\ocr_translate\urls.py", line 22, in <module>
    from ocr_translate import views
  File "C:\OCR\ocr\ocr_translate\ocr_translate\views.py", line 37, in <module>
    from .ocr_tsl.box import get_box_model, load_box_model, unload_box_model
  File "C:\OCR\ocr\ocr_translate\ocr_translate\ocr_tsl\__init__.py", line 27, in <module>
    auto_create_languages()
  File "C:\OCR\ocr\ocr_translate\ocr_translate\ocr_tsl\initializers.py", line 69, in auto_create_languages
    opt_obj, _ = m.OptionDict.objects.get_or_create(options=def_opt)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\db\models\query.py", line 916, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\OCR\ocr\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\OCR\ocr\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\OCR\ocr\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\OCR\ocr\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OCR\ocr\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: ocr_translate_optiondict

```

Here's all the commands I made. All went smoothly up until migrate:
```
PS C:\OCR> python -m venv ocr
PS C:\OCR> cd ocr
PS C:\OCR\ocr> scripts/activate
(ocr) PS C:\OCR\ocr> git clone https://github.com/Crivella/ocr_translate
(ocr) PS C:\OCR\ocr> cd ocr_translate
(ocr) PS C:\OCR\ocr\ocr_translate> pip install -r requirements-torch-cuda.txt
(ocr) PS C:\OCR\ocr\ocr_translate> pip install -r requirements.txt
(ocr) PS C:\OCR\ocr\ocr_translate> pip install -r plugins.txt
(ocr) PS C:\OCR\ocr\ocr_translate> python manage.py migrate

```
OS:
- Edition	Windows 11 Pro
- Version	24H2
- Installed on	‎16/‎06/‎2024
- OS build	26100.1000
- Experience	Windows Feature Experience Pack 1000.26100.6.0
- 
Hardware:
- Processor	AMD Ryzen 5 5600G
- Installed RAM	32,0 GB
- GPU NVIDIA GeForce RTX 3060

Python:
- Python 3.11.9

**Comment by Crivella** [comment]
Umh I've never encountered this error and also tried to rebuild everything from scratch with the same commands but was not able to reproduce it.

A few question to clarify:

- Do you already have a database present? (It might be possible that for some reason an old database is not migrating to a new one)
- What is the output of the migrate command (eg at what 00XX step is it failing?)
- What is the output of `pip freeze` especially in regards to the version of `django-ocr_translate`

A possible solution if you already have a database that is not migrating you could try deleting/renaming it and create a new one.

If you don't have a database already I will have to investigate a little more. A solution that should work for you but is not a general fix is to:

- delete the `ocr_translate/migrations` folder
- run the command `python manage.py makemigrations ocr_translate`
- run the command `python manage.py migrate`

This will crate the multistep migrations (they are there for people to migrate from older release version to new one) and than recreate the steps to create the database as a single operations.

**Comment by JohnKirk1337** [comment]
> * Do you already have a database present? (It might be possible that for some reason an old database is not migrating to a new one)

I don't. Although, when the error occurs, it creates a 0kb sqlite3 database file.
> * What is the output of `python manage.py showmigrations`
>   * In case you do not see any `ocr_translate` related one does `python manage.py showmigrations ocr_translate` helps? (If it does it is possible that running `python manage.py migrate ocr_translate` might help) 

It gives the exact same error in all of those commands.

> * What is the output of `pip freeze` especially in regards to the version of `django-ocr_translate` and `Django`

```
asgiref==3.8.1
certifi==2022.12.7
charset-normalizer==2.1.1
click==8.1.7
colorama==0.4.6
Django==4.2.13
django-ocr_translate==0.5.1
easyocr==1.7.1
filelock==3.13.1
fsspec==2024.6.1
fugashi==1.2.1
huggingface-hub==0.23.4
idna==3.4
imageio==2.34.2
Jinja2==3.1.3
joblib==1.4.2
lazy_loader==0.4
MarkupSafe==2.1.5
mpmath==1.3.0
networkx==3.2.1
ninja==1.11.1.1
numpy==1.24.4
ocr_translate-easyocr==0.3.0
ocr_translate-hugging_face==0.2.1
ocr_translate-tesseract==0.2.0
opencv-python-headless==4.8.0.76
packaging==24.1
Pillow==10.0.1
protobuf==3.20.3
pyclipper==1.3.0.post5
pytesseract==0.3.10
python-bidi==0.4.2
PyYAML==6.0.1
regex==2024.5.15
requests==2.28.1
sacremoses==0.0.53
safetensors==0.3.3
scikit-image==0.24.0
scipy==1.14.0
sentencepiece==0.1.99
shapely==2.0.4
six==1.16.0
sqlparse==0.5.0
sympy==1.12
tifffile==2024.6.18
tokenizers==0.13.3
torch==2.0.1+cu118
torchvision==0.15.2+cu118
tqdm==4.66.4
transformers==4.30.2
typing_extensions==4.9.0
tzdata==2024.1
unidic-lite==1.0.8
urllib3==1.26.13
```

> * delete the `ocr_translate/migrations` folder
> * run the command `python manage.py makemigrations ocr_translate`
> * run the command `python manage.py migrate`

I did it as instructed, but it gives the exact same error.

I just found out that by removing the ocr_translate.urls from the url file, it migrates normally. Tho, that breaks the addon, as the box/ocr/translation models aren't able to be loaded. I hope that helps.
![WindowsTerminal_6AD8sKqo8D](https://github.com/Crivella/ocr_translate/assets/59065439/dc689b95-37a9-4c55-a21b-b7cbeaecc783)

**Comment by Crivella** [comment]
Umh this is weird, I will be travelling tomorrow but will look into it.

In the meantime, If that allows you to run the migrate command, you can try to just re-enable the line afterwards and run the server as it looks like all migrations ran successfully (migrate is a one time thing to create the database or migrate it after a new version)

**Comment by JohnKirk1337** [comment]
> In the meantime, If that allows you to run the migrate command, you can try to just re-enable the line afterwards and run the server as it looks like all migrations ran successfully (migrate is a one time thing to create the database or migrate it after a new version)

I tried, but if I try to run the server with the line enabled it gives the exact same error.

**Comment by Crivella** [comment]
I think i see what is going on for the first part.

I was able to reproduce the exact same error by running `python manage.py migrate` after setting the `AUTOCREATE_LANGUAGES` environment variable. Did you set this variable as well?
In case yes, you are supposed to set the variable after (that variable tells the code to do stuff that requires the database, leading to that error since the database is not there yet)

The problem though should be happening only if you do not have a migrated database, once you have the file `db.sqlite3` (it should be non empty, you can check by opening the file with a tool like [SQliteBrowser](https://sqlitebrowser.org/)), I am not sure why you are still getting the error. (Eg i am able to run the server and also the migration with `AUTOCREATE_LANGUAGES` set to `True` if the db already exists)
The only thing that would come to mind is that you are creating the database but you have also the `DATABASE_NAME` set so you are not using the db you just created.

For the first part I will improve the documentation and possibly add a check that will stop those part of the code form running if the DB has not been created yet.

For the second part let me know if this is the problem or if we need to dig more

**Comment by JohnKirk1337** [comment]
> I was able to reproduce the exact same error by running python manage.py migrate after setting the AUTOCREATE_LANGUAGES environment variable. Did you set this variable as well?
> In case yes, you are supposed to set the variable after

That was it. Removing those variables did it. Tho I was not able to make the ocr_translate-paddle plugin to work and it says to be runnning on the cpu even tho I installed the cuda requirements. But for another issue ticked.
